export const orderSummarySectionTheme = {
  section: "rounded-full border border-[#a3e635]/20 bg-white shadow-sm",
  header: "border-b border-[#a3e635]/15 px-6 py-4",
  title: "font-sans text-lg text-[#0a0a0a]",
  body: "space-y-4 p-6",
  row: "flex items-center justify-between text-base",
  rowLabel: "text-neutral-500",
  rowValue: "font-medium text-[#0a0a0a]",
  discountRow: "flex items-start justify-between text-base",
  discountLeft: "flex flex-col items-start gap-1",
  promoBadge: "rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-xs font-semibold text-emerald-700",
  discountValue: "font-medium text-emerald-700",
  totalRow: "mt-2 flex items-center justify-between border-t border-dashed border-[#a3e635]/25 pt-4",
  totalLabel: "text-lg font-semibold text-[#0a0a0a]",
  totalValue: "font-sans text-2xl font-bold text-[#0a0a0a]",
  footer: "rounded-b-full border-t border-[#a3e635]/15 bg-[#f7fee7]/50 p-4",
  button: "block w-full rounded-full bg-[#0a0a0a] px-4 py-3 text-center text-sm font-semibold uppercase tracking-tight text-[#d9f99d] transition-colors hover:bg-[#1a1a1a] active:scale-[0.98]",
};
