export const orderSummarySectionTheme = {
  section: "rounded-lg border border-[#2563eb]/20 bg-white shadow-sm",
  header: "border-b border-[#2563eb]/15 px-6 py-4",
  title: "font-sans text-lg text-[#111827]",
  body: "space-y-4 p-6",
  row: "flex items-center justify-between text-base",
  rowLabel: "text-slate-500",
  rowValue: "font-medium text-[#111827]",
  discountRow: "flex items-start justify-between text-base",
  discountLeft: "flex flex-col items-start gap-1",
  promoBadge: "rounded-lg border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-xs font-semibold text-emerald-700",
  discountValue: "font-medium text-emerald-700",
  totalRow: "mt-2 flex items-center justify-between border-t border-dashed border-[#2563eb]/25 pt-4",
  totalLabel: "text-lg font-semibold text-[#111827]",
  totalValue: "font-sans text-2xl font-bold text-[#111827]",
  footer: "rounded-b-lg border-t border-[#2563eb]/15 bg-[#eff6ff]/50 p-4",
  button: "block w-full rounded-lg bg-[#111827] px-4 py-3 text-center text-sm font-semibold normal-case tracking-wide text-[#93c5fd] transition-colors hover:bg-[#1e293b] active:scale-[0.98]",
};
