export const aboutPageTheme = {
  main: "min-h-screen bg-white",
  heroSection: "relative overflow-hidden bg-gray-950",
  heroGradient: "absolute inset-0 bg-gradient-to-br from-gray-950 via-gray-900 to-gray-800",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 lg:py-32",
  heroContent: "max-w-3xl",
  badge: "inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-medium text-white backdrop-blur",
  heroTitle: "mt-6 text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl",
  heroDescription: "mt-6 max-w-2xl text-lg leading-8 text-gray-300",
  heroButtons: "mt-8 flex flex-wrap gap-4",
  primaryBtn: "inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3 text-sm font-semibold text-gray-900 transition-colors hover:bg-gray-200",
  secondaryBtn: "inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/5 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-white/10",
  
  storySection: "py-20 sm:py-24",
  storyContainer: "mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8",
  imageWrapper: "relative overflow-hidden rounded-3xl bg-gray-100",
  imageInner: "relative aspect-[4/3]",
  sectionSubtitle: "text-sm font-semibold uppercase tracking-wider text-gray-500",
  sectionTitle: "mt-3 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl",
  sectionText: "mt-6 text-base leading-7 text-gray-600",
  sectionTextSecondary: "mt-4 text-base leading-7 text-gray-600",
  featuresGrid: "mt-8 grid gap-4 sm:grid-cols-2",
  featureItem: "flex items-center gap-3",
  featureIcon: "h-5 w-5 shrink-0 text-gray-700",
  featureText: "text-sm font-medium text-gray-700",

  valuesSection: "border-y border-gray-100 bg-gray-50 py-20 sm:py-24",
  valuesHeader: "mx-auto max-w-2xl text-center",
  valuesGrid: "mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4",
  valueCard: "rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg",
  valueIconBox: "flex h-12 w-12 items-center justify-center rounded-xl bg-gray-100 text-gray-800",
  valueTitle: "mt-5 text-lg font-bold text-gray-900",
  valueDesc: "mt-3 text-sm leading-6 text-gray-600",

  ctaBox: "overflow-hidden rounded-3xl bg-gray-950 px-6 py-14 sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-16",
  ctaTextContainer: "max-w-2xl",
  ctaTitle: "text-3xl font-bold tracking-tight text-white sm:text-4xl",
  ctaDesc: "mt-4 text-base leading-7 text-gray-300",
  ctaButtonWrapper: "mt-8 shrink-0 lg:ms-10 lg:mt-0",
};