export const promoBannerTheme = {
  section: "bg-[#f9f6ef] py-16",
  container: "mx-auto max-w-7xl px-6 lg:px-10",
  bannerWrapper: "relative overflow-hidden rounded-sm bg-[#0c0a07] border border-[#b08d57]/20 shadow-md grid grid-cols-1 md:grid-cols-12 items-stretch min-h-[420px]",
  imageWrapper: "relative md:col-span-5 min-h-[260px] md:min-h-full overflow-hidden",
  image: "absolute inset-0 h-full w-full object-cover opacity-90",
  overlay: "absolute inset-0 bg-gradient-to-r from-[#0c0a07]/30 to-transparent",
  contentWrapper: "md:col-span-7 flex flex-col justify-center items-start p-8 sm:p-12 md:p-16 space-y-6",
  textWrapper: "space-y-3",
  badge: "text-[10px] font-bold uppercase tracking-[0.25em] text-[#b08d57] block",
  title: "font-serif text-3xl tracking-tight sm:text-4xl text-[#f9f6ef] leading-tight",
  description: "max-w-md text-sm text-stone-400 font-light leading-relaxed",
  button: "group relative inline-flex items-center gap-4 bg-transparent border border-[#d4b877]/50 px-8 py-4 text-xs font-semibold uppercase tracking-widest text-[#d4b877] rounded-sm overflow-hidden transition-all hover:bg-[#d4b877] hover:text-[#0c0a07] active:scale-[0.98]",
  buttonArrow: "text-current transition-transform group-hover:translate-x-1",
};
