export const careersTheme = {
  section: "py-16 bg-[#f9f6ef]",
  emptyContainer: "mx-auto max-w-7xl px-4 text-center",
  emptyTitle: "font-serif text-2xl text-[#0c0a07]",
  emptyDescription: "mt-2 text-stone-500",
  container: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8",
  headerWrapper: "mb-10 max-w-2xl",
  badge: "text-sm font-semibold uppercase tracking-wider text-[#b08d57]",
  title: "mt-2 font-serif text-3xl tracking-tight text-[#0c0a07] sm:text-4xl",
  description: "mt-4 text-base leading-7 text-stone-500",
  grid: "grid gap-6 md:grid-cols-2 lg:grid-cols-3",
  card: "group flex h-full flex-col overflow-hidden rounded-sm border border-[#b08d57]/15 bg-white shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-[#b08d57]/40 hover:shadow-xl",
  imageWrapper: "relative h-52 overflow-hidden bg-[#f3ede0]",
  image: "object-cover transition-transform duration-500 group-hover:scale-105",
  imagePlaceholder: "flex h-full items-center justify-center bg-gradient-to-br from-[#f3ede0] to-[#e8dfc9]",
  imagePlaceholderText: "text-sm text-[#b08d57]",
  imageOverlay: "absolute inset-0 bg-gradient-to-t from-black/50 to-transparent",
  experienceBadge: "absolute bottom-4 left-4 rounded-sm bg-[#0c0a07]/90 px-3 py-1 text-xs font-medium text-[#d4b877] shadow-sm backdrop-blur",
  cardBody: "flex flex-1 flex-col p-6",
  role: "mb-2 text-sm font-medium text-[#b08d57]",
  cardTitle: "font-serif text-xl text-[#0c0a07] transition-colors group-hover:text-[#b08d57]",
  cardDescription: "mt-3 line-clamp-3 text-sm leading-6 text-stone-500",
  requirementsWrapper: "mt-5 flex items-center gap-2 text-sm text-stone-500",
  requirementsIcon: "h-4 w-4 text-[#b08d57]",
  actionWrapper: "mt-auto pt-6",
  actionButton: "inline-flex w-full items-center justify-center gap-2 rounded-sm bg-[#0c0a07] px-5 py-3 text-sm font-semibold uppercase tracking-wider text-[#d4b877] transition-colors hover:bg-[#1a1611]",
  actionIcon: "h-4 w-4 transition-transform duration-200 group-hover:translate-x-1 rtl:rotate-180 rtl:group-hover:-translate-x-1",
};
