export const careerDetailsTheme = {
  main: "min-h-screen bg-[#f9f6ef]",
  heroSection: "relative overflow-hidden bg-[#0c0a07]",
  heroImageWrapper: "absolute inset-0",
  heroImage: "object-cover opacity-25",
  heroOverlay: "absolute inset-0 bg-linear-to-r from-[#0c0a07] via-[#0c0a07]/90 to-[#0c0a07]/40",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28",
  backLink: "mb-8 inline-flex items-center gap-2 text-sm font-medium text-[#d4b877]/80 transition hover:text-[#d4b877]",
  backIcon: "h-4 w-4 rtl:rotate-180",
  role: "mb-3 text-sm font-semibold uppercase tracking-widest text-[#b08d57]",
  title: "max-w-4xl font-serif text-4xl tracking-tight text-[#f9f6ef] sm:text-5xl lg:text-6xl",
  metaWrapper: "mt-8 flex flex-wrap gap-3",
  badge: "rounded-sm border border-[#d4b877]/30 bg-white/5 px-4 py-2 text-sm text-[#f9f6ef] backdrop-blur",
  contentSection: "mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8",
  grid: "grid gap-10 lg:grid-cols-[1fr_350px]",
  card: "rounded-sm border border-[#b08d57]/15 bg-white p-6 shadow-sm sm:p-10",
  sectionTitle: "font-serif text-2xl text-[#0c0a07]",
  description: "mt-5 whitespace-pre-line text-base leading-8 text-stone-600",
  requirementsSection: "mt-12 border-t border-[#b08d57]/15 pt-10",
  requirementsList: "mt-6 space-y-4",
  requirementItem: "flex gap-4 text-stone-600",
  requirementIcon: "mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#b08d57]/10 text-xs font-bold text-[#b08d57]",
  requirementText: "leading-7",
  sidebar: "h-fit lg:sticky lg:top-8",
  sidebarCard: "rounded-sm border border-[#b08d57]/15 bg-white p-6 shadow-sm",
  sidebarTitle: "font-serif text-xl text-[#0c0a07]",
  sidebarDescription: "mt-3 text-sm leading-6 text-stone-500",
  applyButton: "mt-6 w-full rounded-sm bg-[#0c0a07] px-5 py-3.5 text-sm font-semibold uppercase tracking-wider text-[#d4b877] transition hover:bg-[#1a1611] text-center block",
  viewAllButton: "mt-3 flex w-full items-center justify-center rounded-sm border border-[#b08d57]/30 px-5 py-3.5 text-sm font-semibold text-[#0c0a07] transition hover:bg-[#f3ede0]",
};
