export const careersTheme = {
  section: "py-16 bg-[#17121f]",
  emptyContainer: "mx-auto max-w-7xl px-4 text-center",
  emptyTitle: "font-mono text-2xl text-[#f5f2fb]",
  emptyDescription: "mt-2 text-violet-400",
  container: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8",
  headerWrapper: "mb-10 max-w-2xl",
  badge: "text-sm font-semibold uppercase tracking-wider text-[#a78bfa]",
  title: "mt-2 font-mono text-3xl tracking-tight text-[#f5f2fb] sm:text-4xl",
  description: "mt-4 text-base leading-7 text-violet-400",
  grid: "grid gap-6 md:grid-cols-2 lg:grid-cols-3",
  card: "group flex h-full flex-col overflow-hidden rounded-none border border-[#a78bfa]/15 bg-white shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-[#a78bfa]/40 hover:shadow-xl",
  imageWrapper: "relative h-52 overflow-hidden bg-[#130e1a]",
  image: "object-cover transition-transform duration-500 group-hover:scale-105",
  imagePlaceholder: "flex h-full items-center justify-center bg-gradient-to-br from-[#130e1a] to-[#0f0b15]",
  imagePlaceholderText: "text-sm text-[#a78bfa]",
  imageOverlay: "absolute inset-0 bg-gradient-to-t from-black/50 to-transparent",
  experienceBadge: "absolute bottom-4 left-4 rounded-none bg-[#f5f2fb]/90 px-3 py-1 text-xs font-medium text-[#3d2b5c] shadow-sm backdrop-blur",
  cardBody: "flex flex-1 flex-col p-6",
  role: "mb-2 text-sm font-medium text-[#a78bfa]",
  cardTitle: "font-mono text-xl text-[#f5f2fb] transition-colors group-hover:text-[#a78bfa]",
  cardDescription: "mt-3 line-clamp-3 text-sm leading-6 text-violet-400",
  requirementsWrapper: "mt-5 flex items-center gap-2 text-sm text-violet-400",
  requirementsIcon: "h-4 w-4 text-[#a78bfa]",
  actionWrapper: "mt-auto pt-6",
  actionButton: "inline-flex w-full items-center justify-center gap-2 rounded-none bg-[#f5f2fb] px-5 py-3 text-sm font-semibold uppercase tracking-wider text-[#3d2b5c] transition-colors hover:bg-[#e6e0f7]",
  actionIcon: "h-4 w-4 transition-transform duration-200 group-hover:translate-x-1 rtl:rotate-180 rtl:group-hover:-translate-x-1",
};
