export const careerDetailsTheme = {
  main: "min-h-screen bg-[#17121f]",
  heroSection: "relative overflow-hidden bg-[#f5f2fb]",
  heroImageWrapper: "absolute inset-0",
  heroImage: "object-cover opacity-25",
  heroOverlay: "absolute inset-0 bg-linear-to-r from-[#f5f2fb] via-[#f5f2fb]/90 to-[#f5f2fb]/40",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28",
  backLink: "mb-8 inline-flex items-center gap-2 text-sm font-medium text-[#3d2b5c]/80 transition hover:text-[#3d2b5c]",
  backIcon: "h-4 w-4 rtl:rotate-180",
  role: "mb-3 text-sm font-semibold uppercase tracking-widest text-[#a78bfa]",
  title: "max-w-4xl font-mono text-4xl tracking-tight text-[#17121f] sm:text-5xl lg:text-6xl",
  metaWrapper: "mt-8 flex flex-wrap gap-3",
  badge: "rounded-none border border-[#3d2b5c]/30 bg-white/5 px-4 py-2 text-sm text-[#17121f] backdrop-blur",
  contentSection: "mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8",
  grid: "grid gap-10 lg:grid-cols-[1fr_350px]",
  card: "rounded-none border border-[#a78bfa]/15 bg-white p-6 shadow-sm sm:p-10",
  sectionTitle: "font-mono text-2xl text-[#f5f2fb]",
  description: "mt-5 whitespace-pre-line text-base leading-8 text-violet-200",
  requirementsSection: "mt-12 border-t border-[#a78bfa]/15 pt-10",
  requirementsList: "mt-6 space-y-4",
  requirementItem: "flex gap-4 text-violet-200",
  requirementIcon: "mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#a78bfa]/10 text-xs font-bold text-[#a78bfa]",
  requirementText: "leading-7",
  sidebar: "h-fit lg:sticky lg:top-8",
  sidebarCard: "rounded-none border border-[#a78bfa]/15 bg-white p-6 shadow-sm",
  sidebarTitle: "font-mono text-xl text-[#f5f2fb]",
  sidebarDescription: "mt-3 text-sm leading-6 text-violet-400",
  applyButton: "mt-6 w-full rounded-none bg-[#f5f2fb] px-5 py-3.5 text-sm font-semibold uppercase tracking-wider text-[#3d2b5c] transition hover:bg-[#e6e0f7] text-center block",
  viewAllButton: "mt-3 flex w-full items-center justify-center rounded-none border border-[#a78bfa]/30 px-5 py-3.5 text-sm font-semibold text-[#f5f2fb] transition hover:bg-[#130e1a]",
};
