export const aboutPageTheme = {
  main: "min-h-screen bg-[#ffffff]",
  heroSection: "relative overflow-hidden bg-[#0a0a0a]",
  heroGradient: "absolute inset-0 bg-gradient-to-br from-[#0a0a0a] via-[#050505] to-[#1a1a1a]",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 lg:py-32",
  heroContent: "max-w-3xl",
  badge: "inline-flex rounded-full border border-[#d9f99d]/30 bg-white/5 px-4 py-2 text-sm font-medium text-[#d9f99d] backdrop-blur",
  heroTitle: "mt-6 font-sans text-4xl tracking-tight text-[#ffffff] sm:text-5xl lg:text-6xl",
  heroDescription: "mt-6 max-w-2xl text-lg leading-8 text-neutral-300 font-light",
  heroButtons: "mt-8 flex flex-wrap gap-4",
  primaryBtn: "inline-flex items-center gap-2 rounded-full bg-[#d9f99d] px-6 py-3 text-sm font-semibold uppercase tracking-tight text-[#0a0a0a] transition-colors hover:bg-[#bef264]",
  secondaryBtn: "inline-flex items-center gap-2 rounded-full border border-[#d9f99d]/40 bg-white/5 px-6 py-3 text-sm font-semibold uppercase tracking-tight text-[#d9f99d] transition-colors hover:bg-white/10",

  storySection: "py-20 sm:py-24",
  storyContainer: "mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8",
  imageWrapper: "relative overflow-hidden rounded-full border border-[#a3e635]/15 bg-[#f7fee7]",
  imageInner: "relative aspect-[4/3]",
  sectionSubtitle: "text-sm font-semibold uppercase tracking-tight text-[#a3e635]",
  sectionTitle: "mt-3 font-sans text-3xl tracking-tight text-[#0a0a0a] sm:text-4xl",
  sectionText: "mt-6 text-base leading-7 text-neutral-600 font-light",
  sectionTextSecondary: "mt-4 text-base leading-7 text-neutral-600 font-light",
  featuresGrid: "mt-8 grid gap-4 sm:grid-cols-2",
  featureItem: "flex items-center gap-3",
  featureIcon: "h-5 w-5 shrink-0 text-[#a3e635]",
  featureText: "text-sm font-medium text-neutral-700",

  valuesSection: "border-y border-[#a3e635]/15 bg-[#f7fee7]/50 py-20 sm:py-24",
  valuesHeader: "mx-auto max-w-2xl text-center",
  valuesGrid: "mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4",
  valueCard: "rounded-full border border-[#a3e635]/15 bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:border-[#a3e635]/35",
  valueIconBox: "flex h-12 w-12 items-center justify-center rounded-full bg-[#f7fee7] text-[#a3e635] border border-[#a3e635]/25",
  valueTitle: "mt-5 font-sans text-lg text-[#0a0a0a]",
  valueDesc: "mt-3 text-sm leading-6 text-neutral-500 font-light",

  ctaBox: "overflow-hidden rounded-full bg-[#0a0a0a] px-6 py-14 sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-16 border border-[#a3e635]/20",
  ctaTextContainer: "max-w-2xl",
  ctaTitle: "font-sans text-3xl tracking-tight text-[#ffffff] sm:text-4xl",
  ctaDesc: "mt-4 text-base leading-7 text-neutral-300 font-light",
  ctaButtonWrapper: "mt-8 shrink-0 lg:ml-10 lg:mt-0",
};