export const aboutPageTheme = {
  main: "min-h-screen bg-[#17121f]",
  heroSection: "relative overflow-hidden bg-[#f5f2fb]",
  heroGradient: "absolute inset-0 bg-gradient-to-br from-[#f5f2fb] via-[#eeeafa] to-[#e6e0f7]",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 lg:py-32",
  heroContent: "max-w-3xl",
  badge: "inline-flex rounded-none border border-[#3d2b5c]/30 bg-white/5 px-4 py-2 text-sm font-medium text-[#3d2b5c] backdrop-blur",
  heroTitle: "mt-6 font-mono text-4xl tracking-tight text-[#17121f] sm:text-5xl lg:text-6xl",
  heroDescription: "mt-6 max-w-2xl text-lg leading-8 text-violet-300 font-light",
  heroButtons: "mt-8 flex flex-wrap gap-4",
  primaryBtn: "inline-flex items-center gap-2 rounded-none bg-[#3d2b5c] px-6 py-3 text-sm font-semibold uppercase tracking-wider text-[#f5f2fb] transition-colors hover:bg-[#2e1f47]",
  secondaryBtn: "inline-flex items-center gap-2 rounded-none border border-[#3d2b5c]/40 bg-white/5 px-6 py-3 text-sm font-semibold uppercase tracking-wider text-[#3d2b5c] transition-colors hover:bg-white/10",

  storySection: "py-20 sm:py-24",
  storyContainer: "mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8",
  imageWrapper: "relative overflow-hidden rounded-none border border-[#a78bfa]/15 bg-[#130e1a]",
  imageInner: "relative aspect-[4/3]",
  sectionSubtitle: "text-sm font-semibold uppercase tracking-wider text-[#a78bfa]",
  sectionTitle: "mt-3 font-mono text-3xl tracking-tight text-[#f5f2fb] sm:text-4xl",
  sectionText: "mt-6 text-base leading-7 text-violet-200 font-light",
  sectionTextSecondary: "mt-4 text-base leading-7 text-violet-200 font-light",
  featuresGrid: "mt-8 grid gap-4 sm:grid-cols-2",
  featureItem: "flex items-center gap-3",
  featureIcon: "h-5 w-5 shrink-0 text-[#a78bfa]",
  featureText: "text-sm font-medium text-violet-100",

  valuesSection: "border-y border-[#a78bfa]/15 bg-[#130e1a]/50 py-20 sm:py-24",
  valuesHeader: "mx-auto max-w-2xl text-center",
  valuesGrid: "mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4",
  valueCard: "rounded-none border border-[#a78bfa]/15 bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:border-[#a78bfa]/35",
  valueIconBox: "flex h-12 w-12 items-center justify-center rounded-full bg-[#130e1a] text-[#a78bfa] border border-[#a78bfa]/25",
  valueTitle: "mt-5 font-mono text-lg text-[#f5f2fb]",
  valueDesc: "mt-3 text-sm leading-6 text-violet-400 font-light",

  ctaBox: "overflow-hidden rounded-none bg-[#f5f2fb] px-6 py-14 sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-16 border border-[#a78bfa]/20",
  ctaTextContainer: "max-w-2xl",
  ctaTitle: "font-mono text-3xl tracking-tight text-[#17121f] sm:text-4xl",
  ctaDesc: "mt-4 text-base leading-7 text-violet-300 font-light",
  ctaButtonWrapper: "mt-8 shrink-0 lg:ml-10 lg:mt-0",
};