export const deliveryInfoSectionTheme = {
  section: "rounded-2xl border border-neutral-200 bg-white shadow-sm",
  header: "border-b border-neutral-100 bg-neutral-50/50 px-6 py-4",
  title: "text-lg font-semibold text-neutral-900",
  body: "p-6",
  grid: "grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8",
  column: "space-y-5",
  fieldWrapper: "",
  fieldLabel: "text-sm text-neutral-500",
  fieldValue: "text-base font-medium text-neutral-900",
  emailValue: "break-all text-base font-medium text-neutral-900",
  noteContainer: "border-t border-neutral-100 pt-5 sm:col-span-2",
  noteLabel: "mb-2 text-sm text-neutral-500",
  noteBox: "rounded-xl border border-amber-100 bg-amber-50/50 p-4",
  noteText: "text-sm leading-relaxed text-amber-900",
};