export const promoBannerTheme = {
  section: "bg-white py-6 sm:pt-8",
  container: "mx-auto max-w-7xl px-6 lg:px-10",
  bannerWrapper: "relative overflow-hidden rounded-3xl sm:rounded-[36px] bg-gradient-to-br from-neutral-50 via-white to-neutral-100/60 border border-neutral-200/70 shadow-xs grid grid-cols-1 md:grid-cols-12 items-stretch min-h-[440px] group",
  imageWrapper: "relative md:col-span-5 min-h-[300px] md:min-h-full overflow-hidden",
  image: "absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-105",
  overlay: "absolute inset-0 bg-gradient-to-t md:bg-gradient-to-r from-neutral-950/30 via-transparent to-transparent",
  contentWrapper: "md:col-span-7 flex flex-col justify-center items-start text-start p-8 sm:p-12 md:p-16 space-y-6",
  textWrapper: "space-y-3.5 max-w-xl",
  badge: "inline-flex items-center gap-2 rounded-full bg-neutral-900/5 border border-neutral-200/80 px-3.5 py-1.5 text-xs font-bold uppercase tracking-wider text-neutral-800",
  title: "text-3xl sm:text-4xl lg:text-[42px] font-extrabold tracking-tight text-neutral-900 leading-[1.15]",
  description: "text-sm sm:text-base text-neutral-600 font-medium leading-relaxed",
  button: "group/btn relative inline-flex items-center gap-3.5 bg-neutral-950 px-8 py-4 text-xs sm:text-sm font-bold  tracking-wider text-white rounded-full overflow-hidden transition-all shadow-sm hover:bg-neutral-800 hover:shadow-md active:scale-[0.98]",
  buttonArrow: "text-neutral-300 transition-transform group-hover/btn:translate-x-1.5 rtl:group-hover/btn:-translate-x-1.5 rtl:rotate-180 inline-block",
};