export const cartTheme = {
  main: "min-h-screen bg-white text-black",
  container: "mx-auto max-w-7xl px-6 py-20 lg:px-10",
  header: "mb-16 border-b border-neutral-100 pb-6",
  title: "text-3xl font-semibold tracking-tight md:text-4xl",
  itemCount: "mt-2 text-xs text-gray-400",
  emptyContainer: "flex flex-col items-center justify-center py-24 text-center",
  emptyText: "mb-6 text-sm text-gray-400",
  emptyButton: "rounded-full bg-black px-8 py-4 text-xs font-semibold uppercase tracking-widest text-white transition hover:bg-neutral-800",
  grid: "grid grid-cols-1 gap-16 lg:grid-cols-12",
  itemsList: "divide-y divide-neutral-100 lg:col-span-7",
  itemCard: "flex gap-6 py-8",
  itemImageWrapper: "relative h-32 w-24 overflow-hidden rounded-2xl bg-neutral-100",
  itemImage: "object-cover",
  itemInfoWrapper: "flex flex-1 flex-col justify-between",
  itemHeader: "flex justify-between gap-4",
  itemTitle: "font-medium",
  itemSubtotal: "font-semibold",
  itemPrice: "mt-1 text-sm text-gray-400",
  itemSku: "mt-1 text-sm text-gray-400",
  itemFooter: "mt-5 flex items-center justify-between",
  quantityWrapper: "flex items-center rounded-full border border-neutral-200",
  quantityButton: "px-4 py-2 text-gray-500 hover:text-black",
  quantityText: "px-3 text-sm font-semibold",
  removeButton: "text-sm text-gray-400 hover:text-black transition",
  summaryColumn: "lg:col-span-5",
  summaryCard: "rounded-[32px] bg-neutral-50 p-8",
  summaryTitle: "mb-6 text-sm font-semibold uppercase tracking-wider",
  summaryRows: "space-y-4 border-b border-neutral-200 pb-6",
  summaryRow: "flex justify-between text-sm",
  summaryValue: "font-semibold",
  totalRow: "flex justify-between py-6",
  totalLabel: "font-medium",
  totalValue: "text-xl font-bold",
  checkoutButton: "block w-full rounded-2xl bg-black py-4 text-center text-xs font-semibold uppercase tracking-widest text-white transition hover:bg-neutral-800",
  continueShoppingLink: "mt-5 flex items-center justify-center gap-2 text-xs text-gray-400 transition hover:text-black",
};