export const careersTheme = {
  section: "py-16",
  emptyContainer: "mx-auto max-w-7xl px-4 text-center",
  emptyTitle: "text-2xl font-semibold text-gray-900",
  emptyDescription: "mt-2 text-gray-500",
  container: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8",
  headerWrapper: "mb-10 max-w-2xl",
  badge: "text-sm font-semibold uppercase tracking-wider text-gray-500",
  title: "mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl",
  description: "mt-4 text-base leading-7 text-gray-600",
  grid: "grid gap-6 md:grid-cols-2 lg:grid-cols-3",
  card: "group flex h-full flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-gray-300 hover:shadow-xl",
  imageWrapper: "relative h-52 overflow-hidden bg-gray-100",
  image: "object-cover transition-transform duration-500 group-hover:scale-105",
  imagePlaceholder: "flex h-full items-center justify-center bg-gradient-to-br from-gray-100 to-gray-200",
  imagePlaceholderText: "text-sm text-gray-400",
  imageOverlay: "absolute inset-0 bg-gradient-to-t from-black/50 to-transparent",
  experienceBadge: "absolute bottom-4 left-4 rounded-full bg-white/95 px-3 py-1 text-xs font-medium text-gray-800 shadow-sm backdrop-blur",
  cardBody: "flex flex-1 flex-col p-6",
  role: "mb-2 text-sm font-medium text-gray-500",
  cardTitle: "text-xl font-bold text-gray-900 transition-colors group-hover:text-gray-700",
  cardDescription: "mt-3 line-clamp-3 text-sm leading-6 text-gray-600",
  requirementsWrapper: "mt-5 flex items-center gap-2 text-sm text-gray-500",
  requirementsIcon: "h-4 w-4 text-gray-500",
  actionWrapper: "mt-auto pt-6",
  actionButton: "inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gray-900 px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-gray-700",
  actionIcon: "h-4 w-4 transition-transform duration-200 group-hover:translate-x-1 rtl:rotate-180 rtl:group-hover:-translate-x-1",
};