export const orderSummaryTheme = {
  container: (isAr: boolean) =>
    `rounded-sm bg-[#f3ede0] p-6 sm:p-8 border border-[#b08d57]/15 ${isAr ? "rtl" : "ltr"}`,
  header: "mb-8",
  title: "text-sm font-semibold uppercase tracking-wider text-[#0c0a07]",
  itemsCount: "mt-2 text-xs text-stone-400",
  itemsList: "space-y-6 border-b border-[#b08d57]/20 pb-8",
  subtotalRow: "flex items-center justify-between pt-6",
  subtotalLabel: "text-sm text-stone-500",
  subtotalValue: "text-sm font-medium text-[#0c0a07]",
  promoSection: "mt-6 border-b border-[#b08d57]/20 pb-6",
  promoFlex: "flex gap-2",
  promoInput: "min-w-0 flex-1 rounded-sm border border-[#b08d57]/25 bg-white px-4 py-3 text-sm outline-none transition focus:border-[#b08d57]",
  promoButton: "rounded-sm bg-[#0c0a07] px-5 py-3 text-xs font-medium uppercase tracking-wider text-[#d4b877] transition hover:bg-[#1a1611] disabled:cursor-not-allowed disabled:opacity-50",
  discountRow: "flex items-center justify-between py-4 text-sm",
  discountLabel: "text-stone-500",
  discountValue: "font-medium text-green-700",
  totalRow: "flex items-center justify-between pt-2",
  totalLabel: "font-medium text-[#0c0a07]",
  totalWrapper: "text-right",
  oldTotalValue: "text-sm text-stone-400 line-through",
  finalTotalValue: "font-serif text-xl font-bold text-[#0c0a07]",
};
