export const careersTheme = {
  section: "py-16 bg-[#eefaf8]",
  emptyContainer: "mx-auto max-w-7xl px-4 text-center",
  emptyTitle: "font-sans text-2xl text-[#0a2e2a]",
  emptyDescription: "mt-2 text-teal-500",
  container: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8",
  headerWrapper: "mb-10 max-w-2xl",
  badge: "text-sm font-semibold normal-case tracking-normal text-[#e8674f]",
  title: "mt-2 font-sans text-3xl tracking-tight text-[#0a2e2a] sm:text-4xl",
  description: "mt-4 text-base leading-7 text-teal-500",
  grid: "grid gap-6 md:grid-cols-2 lg:grid-cols-3",
  card: "group flex h-full flex-col overflow-hidden rounded-2xl border border-[#e8674f]/15 bg-white shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-[#e8674f]/40 hover:shadow-xl",
  imageWrapper: "relative h-52 overflow-hidden bg-[#d9f0ec]",
  image: "object-cover transition-transform duration-500 group-hover:scale-105",
  imagePlaceholder: "flex h-full items-center justify-center bg-gradient-to-br from-[#d9f0ec] to-[#c3e8e2]",
  imagePlaceholderText: "text-sm text-[#e8674f]",
  imageOverlay: "absolute inset-0 bg-gradient-to-t from-black/50 to-transparent",
  experienceBadge: "absolute bottom-4 left-4 rounded-2xl bg-[#0a2e2a]/90 px-3 py-1 text-xs font-medium text-[#f7c9a3] shadow-sm backdrop-blur",
  cardBody: "flex flex-1 flex-col p-6",
  role: "mb-2 text-sm font-medium text-[#e8674f]",
  cardTitle: "font-sans text-xl text-[#0a2e2a] transition-colors group-hover:text-[#e8674f]",
  cardDescription: "mt-3 line-clamp-3 text-sm leading-6 text-teal-500",
  requirementsWrapper: "mt-5 flex items-center gap-2 text-sm text-teal-500",
  requirementsIcon: "h-4 w-4 text-[#e8674f]",
  actionWrapper: "mt-auto pt-6",
  actionButton: "inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#0a2e2a] px-5 py-3 text-sm font-semibold normal-case tracking-normal text-[#f7c9a3] transition-colors hover:bg-[#072220]",
  actionIcon: "h-4 w-4 transition-transform duration-200 group-hover:translate-x-1 rtl:rotate-180 rtl:group-hover:-translate-x-1",
};
