export const careerDetailsTheme = {
  main: "min-h-screen bg-[#eefaf8]",
  heroSection: "relative overflow-hidden bg-[#0a2e2a]",
  heroImageWrapper: "absolute inset-0",
  heroImage: "object-cover opacity-25",
  heroOverlay: "absolute inset-0 bg-linear-to-r from-[#0a2e2a] via-[#0a2e2a]/90 to-[#0a2e2a]/40",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28",
  backLink: "mb-8 inline-flex items-center gap-2 text-sm font-medium text-[#f7c9a3]/80 transition hover:text-[#f7c9a3]",
  backIcon: "h-4 w-4 rtl:rotate-180",
  role: "mb-3 text-sm font-semibold normal-case tracking-normal text-[#e8674f]",
  title: "max-w-4xl font-sans text-4xl tracking-tight text-[#eefaf8] sm:text-5xl lg:text-6xl",
  metaWrapper: "mt-8 flex flex-wrap gap-3",
  badge: "rounded-2xl border border-[#f7c9a3]/30 bg-white/5 px-4 py-2 text-sm text-[#eefaf8] backdrop-blur",
  contentSection: "mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8",
  grid: "grid gap-10 lg:grid-cols-[1fr_350px]",
  card: "rounded-2xl border border-[#e8674f]/15 bg-white p-6 shadow-sm sm:p-10",
  sectionTitle: "font-sans text-2xl text-[#0a2e2a]",
  description: "mt-5 whitespace-pre-line text-base leading-8 text-teal-600",
  requirementsSection: "mt-12 border-t border-[#e8674f]/15 pt-10",
  requirementsList: "mt-6 space-y-4",
  requirementItem: "flex gap-4 text-teal-600",
  requirementIcon: "mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#e8674f]/10 text-xs font-bold text-[#e8674f]",
  requirementText: "leading-7",
  sidebar: "h-fit lg:sticky lg:top-8",
  sidebarCard: "rounded-2xl border border-[#e8674f]/15 bg-white p-6 shadow-sm",
  sidebarTitle: "font-sans text-xl text-[#0a2e2a]",
  sidebarDescription: "mt-3 text-sm leading-6 text-teal-500",
  applyButton: "mt-6 w-full rounded-2xl bg-[#0a2e2a] px-5 py-3.5 text-sm font-semibold normal-case tracking-normal text-[#f7c9a3] transition hover:bg-[#072220] text-center block",
  viewAllButton: "mt-3 flex w-full items-center justify-center rounded-2xl border border-[#e8674f]/30 px-5 py-3.5 text-sm font-semibold text-[#0a2e2a] transition hover:bg-[#d9f0ec]",
};
