export const aboutPageTheme = {
  main: "min-h-screen bg-[#ffffff]",
  heroSection: "relative overflow-hidden bg-[#111827]",
  heroGradient: "absolute inset-0 bg-gradient-to-br from-[#111827] via-[#0f172a] to-[#1e293b]",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 lg:py-32",
  heroContent: "max-w-3xl",
  badge: "inline-flex rounded-lg border border-[#93c5fd]/30 bg-white/5 px-4 py-2 text-sm font-medium text-[#93c5fd] backdrop-blur",
  heroTitle: "mt-6 font-sans text-4xl tracking-tight text-[#ffffff] sm:text-5xl lg:text-6xl",
  heroDescription: "mt-6 max-w-2xl text-lg leading-8 text-slate-300 font-light",
  heroButtons: "mt-8 flex flex-wrap gap-4",
  primaryBtn: "inline-flex items-center gap-2 rounded-lg bg-[#93c5fd] px-6 py-3 text-sm font-semibold normal-case tracking-wide text-[#111827] transition-colors hover:bg-[#60a5fa]",
  secondaryBtn: "inline-flex items-center gap-2 rounded-lg border border-[#93c5fd]/40 bg-white/5 px-6 py-3 text-sm font-semibold normal-case tracking-wide text-[#93c5fd] transition-colors hover:bg-white/10",

  storySection: "py-20 sm:py-24",
  storyContainer: "mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8",
  imageWrapper: "relative overflow-hidden rounded-lg border border-[#2563eb]/15 bg-[#eff6ff]",
  imageInner: "relative aspect-[4/3]",
  sectionSubtitle: "text-sm font-semibold normal-case tracking-wide text-[#2563eb]",
  sectionTitle: "mt-3 font-sans text-3xl tracking-tight text-[#111827] sm:text-4xl",
  sectionText: "mt-6 text-base leading-7 text-slate-600 font-light",
  sectionTextSecondary: "mt-4 text-base leading-7 text-slate-600 font-light",
  featuresGrid: "mt-8 grid gap-4 sm:grid-cols-2",
  featureItem: "flex items-center gap-3",
  featureIcon: "h-5 w-5 shrink-0 text-[#2563eb]",
  featureText: "text-sm font-medium text-slate-700",

  valuesSection: "border-y border-[#2563eb]/15 bg-[#eff6ff]/50 py-20 sm:py-24",
  valuesHeader: "mx-auto max-w-2xl text-center",
  valuesGrid: "mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4",
  valueCard: "rounded-lg border border-[#2563eb]/15 bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:border-[#2563eb]/35",
  valueIconBox: "flex h-12 w-12 items-center justify-center rounded-full bg-[#eff6ff] text-[#2563eb] border border-[#2563eb]/25",
  valueTitle: "mt-5 font-sans text-lg text-[#111827]",
  valueDesc: "mt-3 text-sm leading-6 text-slate-500 font-light",

  ctaBox: "overflow-hidden rounded-lg bg-[#111827] px-6 py-14 sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-16 border border-[#2563eb]/20",
  ctaTextContainer: "max-w-2xl",
  ctaTitle: "font-sans text-3xl tracking-tight text-[#ffffff] sm:text-4xl",
  ctaDesc: "mt-4 text-base leading-7 text-slate-300 font-light",
  ctaButtonWrapper: "mt-8 shrink-0 lg:ml-10 lg:mt-0",
};