export const cartTheme = {
  main: "min-h-screen bg-[#ffffff] text-[#111827]",
  container: "mx-auto max-w-7xl px-6 py-20 lg:px-10",
  header: "mb-16 border-b border-[#2563eb]/15 pb-6",
  title: "font-sans text-3xl tracking-tight md:text-4xl",
  itemCount: "mt-2 text-xs text-slate-400 normal-case tracking-wide",
  emptyContainer: "flex flex-col items-center justify-center py-24 text-center",
  emptyText: "mb-6 text-sm text-slate-400",
  emptyButton: "rounded-lg border border-[#93c5fd]/40 bg-[#111827] px-8 py-4 text-xs font-semibold normal-case tracking-wide text-[#93c5fd] transition hover:bg-[#1e293b]",
  grid: "grid grid-cols-1 gap-16 lg:grid-cols-12",
  itemsList: "divide-y divide-[#2563eb]/15 lg:col-span-7",
  itemCard: "flex gap-6 py-8",
  itemImageWrapper: "relative h-32 w-24 overflow-hidden rounded-lg bg-[#eff6ff]",
  itemImage: "object-cover",
  itemInfoWrapper: "flex flex-1 flex-col justify-between",
  itemHeader: "flex justify-between gap-4",
  itemTitle: "font-sans text-base",
  itemSubtotal: "font-semibold",
  itemPrice: "mt-1 text-sm text-slate-400",
  itemSku: "mt-1 text-sm text-slate-400",
  itemFooter: "mt-5 flex items-center justify-between",
  quantityWrapper: "flex items-center rounded-full border border-[#2563eb]/25",
  quantityButton: "px-4 py-2 text-slate-400 hover:text-[#2563eb]",
  quantityText: "px-3 text-sm font-semibold",
  removeButton: "text-sm text-slate-400 hover:text-[#2563eb] transition",
  summaryColumn: "lg:col-span-5",
  summaryCard: "rounded-lg bg-[#eff6ff] p-8 border border-[#2563eb]/15",
  summaryTitle: "mb-6 text-sm font-semibold normal-case tracking-wide text-[#111827]",
  summaryRows: "space-y-4 border-b border-[#2563eb]/20 pb-6",
  summaryRow: "flex justify-between text-sm",
  summaryValue: "font-semibold",
  totalRow: "flex justify-between py-6",
  totalLabel: "font-medium",
  totalValue: "font-sans text-xl font-bold",
  checkoutButton: "block w-full rounded-lg bg-[#111827] py-4 text-center text-xs font-semibold normal-case tracking-wide text-[#93c5fd] transition hover:bg-[#1e293b]",
  continueShoppingLink: "mt-5 flex items-center justify-center gap-2 text-xs text-slate-400 transition hover:text-[#2563eb]",
};
