export const heroTheme = {
  main: "relative w-full overflow-hidden bg-[#111827]",
  section: "relative h-150 w-full md:h-170",
  slide: "absolute inset-0 h-full w-full transition-opacity duration-1000 ease-in-out",
  slideActive: "opacity-100 z-10",
  slideInactive: "opacity-0 z-0",
  image: "object-cover object-center",
  overlay: "absolute inset-0 bg-black/50 backdrop-blur-[1px]",
  contentWrapper: "absolute inset-0 flex items-center",
  container: "mx-auto w-full max-w-7xl px-8 lg:px-16",
  article: "max-w-2xl space-y-6 text-[#ffffff]",
  header: "space-y-4",
  title: "font-sans text-4xl font-normal leading-tight tracking-tight md:text-6xl lg:text-7xl",
  nav: "flex gap-4 pt-4",
  shopButton: "rounded-lg border border-[#93c5fd]/50 bg-transparent px-8 py-3.5 text-sm normal-case tracking-wide font-medium text-[#93c5fd] transition hover:bg-[#93c5fd] hover:text-[#111827] shadow-sm",
  indicatorsWrapper: "absolute bottom-8 left-0 right-0 z-20 flex justify-center gap-3",
  indicator: "h-[2px] transition-all duration-500",
  indicatorActive: "w-8 bg-[#93c5fd]",
  indicatorInactive: "w-2 bg-white/30",
};
