export const careerDetailsTheme = {
  main: "min-h-screen bg-gray-50",
  heroSection: "relative overflow-hidden bg-gray-950",
  heroImageWrapper: "absolute inset-0",
  heroImage: "object-cover opacity-30",
  heroOverlay: "absolute inset-0 bg-linear-to-r from-gray-950 via-gray-950/90 to-gray-950/40",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28",
  backLink: "mb-8 inline-flex items-center gap-2 text-sm font-medium text-white/70 transition hover:text-white",
  backIcon: "h-4 w-4 rtl:rotate-180",
  role: "mb-3 text-sm font-semibold uppercase tracking-widest text-primary-400",
  title: "max-w-4xl text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl",
  metaWrapper: "mt-8 flex flex-wrap gap-3",
  badge: "rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm text-white backdrop-blur",
  contentSection: "mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8",
  grid: "grid gap-10 lg:grid-cols-[1fr_350px]",
  card: "rounded-3xl border border-gray-200 bg-white p-6 shadow-sm sm:p-10",
  sectionTitle: "text-2xl font-bold text-gray-900",
  description: "mt-5 whitespace-pre-line text-base leading-8 text-gray-600",
  requirementsSection: "mt-12 border-t border-gray-100 pt-10",
  requirementsList: "mt-6 space-y-4",
  requirementItem: "flex gap-4 text-gray-600",
  requirementIcon: "mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary",
  requirementText: "leading-7",
  sidebar: "h-fit lg:sticky lg:top-8",
  sidebarCard: "rounded-3xl border border-gray-200 bg-white p-6 shadow-sm",
  sidebarTitle: "text-xl font-bold text-gray-900",
  sidebarDescription: "mt-3 text-sm leading-6 text-gray-500",
  applyButton: "mt-6 w-full rounded-xl bg-gray-900 px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-primary text-center block",
  viewAllButton: "mt-3 flex w-full items-center justify-center rounded-xl border border-gray-200 px-5 py-3.5 text-sm font-semibold text-gray-700 transition hover:bg-gray-50",
};