export const aboutPageTheme = {
  main: "min-h-screen bg-[#f9f6ef]",
  heroSection: "relative overflow-hidden bg-[#0c0a07]",
  heroGradient: "absolute inset-0 bg-gradient-to-br from-[#0c0a07] via-[#171310] to-[#1a1611]",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 lg:py-32",
  heroContent: "max-w-3xl",
  badge: "inline-flex rounded-sm border border-[#d4b877]/30 bg-white/5 px-4 py-2 text-sm font-medium text-[#d4b877] backdrop-blur",
  heroTitle: "mt-6 font-serif text-4xl tracking-tight text-[#f9f6ef] sm:text-5xl lg:text-6xl",
  heroDescription: "mt-6 max-w-2xl text-lg leading-8 text-stone-300 font-light",
  heroButtons: "mt-8 flex flex-wrap gap-4",
  primaryBtn: "inline-flex items-center gap-2 rounded-sm bg-[#d4b877] px-6 py-3 text-sm font-semibold uppercase tracking-wider text-[#0c0a07] transition-colors hover:bg-[#c9a869]",
  secondaryBtn: "inline-flex items-center gap-2 rounded-sm border border-[#d4b877]/40 bg-white/5 px-6 py-3 text-sm font-semibold uppercase tracking-wider text-[#d4b877] transition-colors hover:bg-white/10",

  storySection: "py-20 sm:py-24",
  storyContainer: "mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8",
  imageWrapper: "relative overflow-hidden rounded-sm border border-[#b08d57]/15 bg-[#f3ede0]",
  imageInner: "relative aspect-[4/3]",
  sectionSubtitle: "text-sm font-semibold uppercase tracking-wider text-[#b08d57]",
  sectionTitle: "mt-3 font-serif text-3xl tracking-tight text-[#0c0a07] sm:text-4xl",
  sectionText: "mt-6 text-base leading-7 text-stone-600 font-light",
  sectionTextSecondary: "mt-4 text-base leading-7 text-stone-600 font-light",
  featuresGrid: "mt-8 grid gap-4 sm:grid-cols-2",
  featureItem: "flex items-center gap-3",
  featureIcon: "h-5 w-5 shrink-0 text-[#b08d57]",
  featureText: "text-sm font-medium text-stone-700",

  valuesSection: "border-y border-[#b08d57]/15 bg-[#f3ede0]/50 py-20 sm:py-24",
  valuesHeader: "mx-auto max-w-2xl text-center",
  valuesGrid: "mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4",
  valueCard: "rounded-sm border border-[#b08d57]/15 bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:border-[#b08d57]/35",
  valueIconBox: "flex h-12 w-12 items-center justify-center rounded-full bg-[#f3ede0] text-[#b08d57] border border-[#b08d57]/25",
  valueTitle: "mt-5 font-serif text-lg text-[#0c0a07]",
  valueDesc: "mt-3 text-sm leading-6 text-stone-500 font-light",

  ctaBox: "overflow-hidden rounded-sm bg-[#0c0a07] px-6 py-14 sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-16 border border-[#b08d57]/20",
  ctaTextContainer: "max-w-2xl",
  ctaTitle: "font-serif text-3xl tracking-tight text-[#f9f6ef] sm:text-4xl",
  ctaDesc: "mt-4 text-base leading-7 text-stone-300 font-light",
  ctaButtonWrapper: "mt-8 shrink-0 lg:ml-10 lg:mt-0",
};