export const cartTheme = {
  main: "min-h-screen bg-[#ffffff] text-[#0a0a0a]",
  container: "mx-auto max-w-7xl px-6 py-20 lg:px-10",
  header: "mb-16 border-b border-[#a3e635]/15 pb-6",
  title: "font-sans text-3xl tracking-tight md:text-4xl",
  itemCount: "mt-2 text-xs text-neutral-400 uppercase tracking-tight",
  emptyContainer: "flex flex-col items-center justify-center py-24 text-center",
  emptyText: "mb-6 text-sm text-neutral-400",
  emptyButton: "rounded-full border border-[#d9f99d]/40 bg-[#0a0a0a] px-8 py-4 text-xs font-semibold uppercase tracking-tight text-[#d9f99d] transition hover:bg-[#1a1a1a]",
  grid: "grid grid-cols-1 gap-16 lg:grid-cols-12",
  itemsList: "divide-y divide-[#a3e635]/15 lg:col-span-7",
  itemCard: "flex gap-6 py-8",
  itemImageWrapper: "relative h-32 w-24 overflow-hidden rounded-full bg-[#f7fee7]",
  itemImage: "object-cover",
  itemInfoWrapper: "flex flex-1 flex-col justify-between",
  itemHeader: "flex justify-between gap-4",
  itemTitle: "font-sans text-base",
  itemSubtotal: "font-semibold",
  itemPrice: "mt-1 text-sm text-neutral-400",
  itemSku: "mt-1 text-sm text-neutral-400",
  itemFooter: "mt-5 flex items-center justify-between",
  quantityWrapper: "flex items-center rounded-full border border-[#a3e635]/25",
  quantityButton: "px-4 py-2 text-neutral-400 hover:text-[#a3e635]",
  quantityText: "px-3 text-sm font-semibold",
  removeButton: "text-sm text-neutral-400 hover:text-[#a3e635] transition",
  summaryColumn: "lg:col-span-5",
  summaryCard: "rounded-full bg-[#f7fee7] p-8 border border-[#a3e635]/15",
  summaryTitle: "mb-6 text-sm font-semibold uppercase tracking-tight text-[#0a0a0a]",
  summaryRows: "space-y-4 border-b border-[#a3e635]/20 pb-6",
  summaryRow: "flex justify-between text-sm",
  summaryValue: "font-semibold",
  totalRow: "flex justify-between py-6",
  totalLabel: "font-medium",
  totalValue: "font-sans text-xl font-bold",
  checkoutButton: "block w-full rounded-full bg-[#0a0a0a] py-4 text-center text-xs font-semibold uppercase tracking-tight text-[#d9f99d] transition hover:bg-[#1a1a1a]",
  continueShoppingLink: "mt-5 flex items-center justify-center gap-2 text-xs text-neutral-400 transition hover:text-[#a3e635]",
};
