export const deliveryInfoSectionTheme = {
  section: "rounded-none border border-[#a78bfa]/20 bg-white shadow-sm",
  header: "border-b border-[#a78bfa]/15 bg-[#130e1a]/40 px-6 py-4",
  title: "font-mono text-lg text-[#f5f2fb]",
  body: "p-6",
  grid: "grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8",
  column: "space-y-5",
  fieldWrapper: "",
  fieldLabel: "text-sm text-violet-400",
  fieldValue: "text-base font-medium text-[#f5f2fb]",
  emailValue: "break-all text-base font-medium text-[#f5f2fb]",
  noteContainer: "border-t border-[#a78bfa]/15 pt-5 sm:col-span-2",
  noteLabel: "mb-2 text-sm text-violet-400",
  noteBox: "rounded-none border border-[#a78bfa]/25 bg-[#130e1a]/50 p-4",
  noteText: "text-sm leading-relaxed text-[#6d28d9]",
};
