export const cartTheme = {
  main: "min-h-screen bg-[#f9f6ef] text-[#0c0a07]",
  container: "mx-auto max-w-7xl px-6 py-20 lg:px-10",
  header: "mb-16 border-b border-[#b08d57]/15 pb-6",
  title: "font-serif text-3xl tracking-tight md:text-4xl",
  itemCount: "mt-2 text-xs text-stone-400 uppercase tracking-wider",
  emptyContainer: "flex flex-col items-center justify-center py-24 text-center",
  emptyText: "mb-6 text-sm text-stone-400",
  emptyButton: "rounded-sm border border-[#d4b877]/40 bg-[#0c0a07] px-8 py-4 text-xs font-semibold uppercase tracking-widest text-[#d4b877] transition hover:bg-[#1a1611]",
  grid: "grid grid-cols-1 gap-16 lg:grid-cols-12",
  itemsList: "divide-y divide-[#b08d57]/15 lg:col-span-7",
  itemCard: "flex gap-6 py-8",
  itemImageWrapper: "relative h-32 w-24 overflow-hidden rounded-sm bg-[#f3ede0]",
  itemImage: "object-cover",
  itemInfoWrapper: "flex flex-1 flex-col justify-between",
  itemHeader: "flex justify-between gap-4",
  itemTitle: "font-serif text-base",
  itemSubtotal: "font-semibold",
  itemPrice: "mt-1 text-sm text-stone-400",
  itemSku: "mt-1 text-sm text-stone-400",
  itemFooter: "mt-5 flex items-center justify-between",
  quantityWrapper: "flex items-center rounded-full border border-[#b08d57]/25",
  quantityButton: "px-4 py-2 text-stone-400 hover:text-[#b08d57]",
  quantityText: "px-3 text-sm font-semibold",
  removeButton: "text-sm text-stone-400 hover:text-[#b08d57] transition",
  summaryColumn: "lg:col-span-5",
  summaryCard: "rounded-sm bg-[#f3ede0] p-8 border border-[#b08d57]/15",
  summaryTitle: "mb-6 text-sm font-semibold uppercase tracking-wider text-[#0c0a07]",
  summaryRows: "space-y-4 border-b border-[#b08d57]/20 pb-6",
  summaryRow: "flex justify-between text-sm",
  summaryValue: "font-semibold",
  totalRow: "flex justify-between py-6",
  totalLabel: "font-medium",
  totalValue: "font-serif text-xl font-bold",
  checkoutButton: "block w-full rounded-sm bg-[#0c0a07] py-4 text-center text-xs font-semibold uppercase tracking-widest text-[#d4b877] transition hover:bg-[#1a1611]",
  continueShoppingLink: "mt-5 flex items-center justify-center gap-2 text-xs text-stone-400 transition hover:text-[#b08d57]",
};
