export const careersTheme = {
  section: "py-16 bg-[#ffffff]",
  emptyContainer: "mx-auto max-w-7xl px-4 text-center",
  emptyTitle: "font-sans text-2xl text-[#0a0a0a]",
  emptyDescription: "mt-2 text-neutral-500",
  container: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8",
  headerWrapper: "mb-10 max-w-2xl",
  badge: "text-sm font-semibold uppercase tracking-tight text-[#a3e635]",
  title: "mt-2 font-sans text-3xl tracking-tight text-[#0a0a0a] sm:text-4xl",
  description: "mt-4 text-base leading-7 text-neutral-500",
  grid: "grid gap-6 md:grid-cols-2 lg:grid-cols-3",
  card: "group flex h-full flex-col overflow-hidden rounded-full border border-[#a3e635]/15 bg-white shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-[#a3e635]/40 hover:shadow-xl",
  imageWrapper: "relative h-52 overflow-hidden bg-[#f7fee7]",
  image: "object-cover transition-transform duration-500 group-hover:scale-105",
  imagePlaceholder: "flex h-full items-center justify-center bg-gradient-to-br from-[#f7fee7] to-[#ecfccb]",
  imagePlaceholderText: "text-sm text-[#a3e635]",
  imageOverlay: "absolute inset-0 bg-gradient-to-t from-black/50 to-transparent",
  experienceBadge: "absolute bottom-4 left-4 rounded-full bg-[#0a0a0a]/90 px-3 py-1 text-xs font-medium text-[#d9f99d] shadow-sm backdrop-blur",
  cardBody: "flex flex-1 flex-col p-6",
  role: "mb-2 text-sm font-medium text-[#a3e635]",
  cardTitle: "font-sans text-xl text-[#0a0a0a] transition-colors group-hover:text-[#a3e635]",
  cardDescription: "mt-3 line-clamp-3 text-sm leading-6 text-neutral-500",
  requirementsWrapper: "mt-5 flex items-center gap-2 text-sm text-neutral-500",
  requirementsIcon: "h-4 w-4 text-[#a3e635]",
  actionWrapper: "mt-auto pt-6",
  actionButton: "inline-flex w-full items-center justify-center gap-2 rounded-full bg-[#0a0a0a] px-5 py-3 text-sm font-semibold uppercase tracking-tight text-[#d9f99d] transition-colors hover:bg-[#1a1a1a]",
  actionIcon: "h-4 w-4 transition-transform duration-200 group-hover:translate-x-1 rtl:rotate-180 rtl:group-hover:-translate-x-1",
};
