export const aboutPageTheme = {
  main: "min-h-screen bg-[#eefaf8]",
  heroSection: "relative overflow-hidden bg-[#0a2e2a]",
  heroGradient: "absolute inset-0 bg-gradient-to-br from-[#0a2e2a] via-[#041917] to-[#072220]",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 lg:py-32",
  heroContent: "max-w-3xl",
  badge: "inline-flex rounded-2xl border border-[#f7c9a3]/30 bg-white/5 px-4 py-2 text-sm font-medium text-[#f7c9a3] backdrop-blur",
  heroTitle: "mt-6 font-sans text-4xl tracking-tight text-[#eefaf8] sm:text-5xl lg:text-6xl",
  heroDescription: "mt-6 max-w-2xl text-lg leading-8 text-teal-300 font-light",
  heroButtons: "mt-8 flex flex-wrap gap-4",
  primaryBtn: "inline-flex items-center gap-2 rounded-2xl bg-[#f7c9a3] px-6 py-3 text-sm font-semibold normal-case tracking-normal text-[#0a2e2a] transition-colors hover:bg-[#f0906f]",
  secondaryBtn: "inline-flex items-center gap-2 rounded-2xl border border-[#f7c9a3]/40 bg-white/5 px-6 py-3 text-sm font-semibold normal-case tracking-normal text-[#f7c9a3] transition-colors hover:bg-white/10",

  storySection: "py-20 sm:py-24",
  storyContainer: "mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8",
  imageWrapper: "relative overflow-hidden rounded-2xl border border-[#e8674f]/15 bg-[#d9f0ec]",
  imageInner: "relative aspect-[4/3]",
  sectionSubtitle: "text-sm font-semibold normal-case tracking-normal text-[#e8674f]",
  sectionTitle: "mt-3 font-sans text-3xl tracking-tight text-[#0a2e2a] sm:text-4xl",
  sectionText: "mt-6 text-base leading-7 text-teal-600 font-light",
  sectionTextSecondary: "mt-4 text-base leading-7 text-teal-600 font-light",
  featuresGrid: "mt-8 grid gap-4 sm:grid-cols-2",
  featureItem: "flex items-center gap-3",
  featureIcon: "h-5 w-5 shrink-0 text-[#e8674f]",
  featureText: "text-sm font-medium text-teal-700",

  valuesSection: "border-y border-[#e8674f]/15 bg-[#d9f0ec]/50 py-20 sm:py-24",
  valuesHeader: "mx-auto max-w-2xl text-center",
  valuesGrid: "mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4",
  valueCard: "rounded-2xl border border-[#e8674f]/15 bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:border-[#e8674f]/35",
  valueIconBox: "flex h-12 w-12 items-center justify-center rounded-full bg-[#d9f0ec] text-[#e8674f] border border-[#e8674f]/25",
  valueTitle: "mt-5 font-sans text-lg text-[#0a2e2a]",
  valueDesc: "mt-3 text-sm leading-6 text-teal-500 font-light",

  ctaBox: "overflow-hidden rounded-2xl bg-[#0a2e2a] px-6 py-14 sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-16 border border-[#e8674f]/20",
  ctaTextContainer: "max-w-2xl",
  ctaTitle: "font-sans text-3xl tracking-tight text-[#eefaf8] sm:text-4xl",
  ctaDesc: "mt-4 text-base leading-7 text-teal-300 font-light",
  ctaButtonWrapper: "mt-8 shrink-0 lg:ml-10 lg:mt-0",
};