export const forgotPasswordPageTheme = {
  main: "flex min-h-screen items-center justify-center bg-[#d9f0ec]/40 px-4 py-12",
  card: "w-full max-w-md rounded-2xl border border-[#e8674f]/15 bg-white p-8 text-center shadow-sm sm:p-10",
  successWrapper: "flex flex-col items-center animate-in fade-in zoom-in duration-500",
  successIconWrapper: "mb-6 flex h-14 w-14 items-center justify-center rounded-full bg-[#e8674f]/10 text-[#e8674f]",
  successIcon: "h-6 w-6",
  title: "font-sans text-2xl tracking-tight text-[#0a2e2a]",
  subtitle: "mt-2 text-sm font-light text-teal-500",
  successButton: "mt-8 inline-block w-full rounded-2xl bg-[#0a2e2a] py-4 text-[11px] font-bold normal-case tracking-normal text-[#f7c9a3] transition-all hover:bg-[#072220] active:scale-[0.98]",
  formStateWrapper: "animate-in fade-in duration-300 text-left",
  header: "mb-8 text-center",
  form: "space-y-5",
  submitButton: "mt-6 w-full rounded-2xl bg-[#0a2e2a] py-4 text-[11px] font-bold normal-case tracking-normal text-[#f7c9a3] transition-all hover:bg-[#072220] active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-50",
  backLinkWrapper: "mt-8 text-center",
  backLink: "text-xs font-medium text-teal-500 transition hover:text-[#e8674f]",
};