export const cartTheme = {
  main: "min-h-screen bg-[#17121f] text-[#f5f2fb]",
  container: "mx-auto max-w-7xl px-6 py-20 lg:px-10",
  header: "mb-16 border-b border-[#a78bfa]/15 pb-6",
  title: "font-mono text-3xl tracking-tight md:text-4xl",
  itemCount: "mt-2 text-xs text-violet-300 uppercase tracking-wider",
  emptyContainer: "flex flex-col items-center justify-center py-24 text-center",
  emptyText: "mb-6 text-sm text-violet-300",
  emptyButton: "rounded-none border border-[#3d2b5c]/40 bg-[#f5f2fb] px-8 py-4 text-xs font-semibold uppercase tracking-widest text-[#3d2b5c] transition hover:bg-[#e6e0f7]",
  grid: "grid grid-cols-1 gap-16 lg:grid-cols-12",
  itemsList: "divide-y divide-[#a78bfa]/15 lg:col-span-7",
  itemCard: "flex gap-6 py-8",
  itemImageWrapper: "relative h-32 w-24 overflow-hidden rounded-none bg-[#130e1a]",
  itemImage: "object-cover",
  itemInfoWrapper: "flex flex-1 flex-col justify-between",
  itemHeader: "flex justify-between gap-4",
  itemTitle: "font-mono text-base",
  itemSubtotal: "font-semibold",
  itemPrice: "mt-1 text-sm text-violet-300",
  itemSku: "mt-1 text-sm text-violet-300",
  itemFooter: "mt-5 flex items-center justify-between",
  quantityWrapper: "flex items-center rounded-full border border-[#a78bfa]/25",
  quantityButton: "px-4 py-2 text-violet-300 hover:text-[#a78bfa]",
  quantityText: "px-3 text-sm font-semibold",
  removeButton: "text-sm text-violet-300 hover:text-[#a78bfa] transition",
  summaryColumn: "lg:col-span-5",
  summaryCard: "rounded-none bg-[#130e1a] p-8 border border-[#a78bfa]/15",
  summaryTitle: "mb-6 text-sm font-semibold uppercase tracking-wider text-[#f5f2fb]",
  summaryRows: "space-y-4 border-b border-[#a78bfa]/20 pb-6",
  summaryRow: "flex justify-between text-sm",
  summaryValue: "font-semibold",
  totalRow: "flex justify-between py-6",
  totalLabel: "font-medium",
  totalValue: "font-mono text-xl font-bold",
  checkoutButton: "block w-full rounded-none bg-[#f5f2fb] py-4 text-center text-xs font-semibold uppercase tracking-widest text-[#3d2b5c] transition hover:bg-[#e6e0f7]",
  continueShoppingLink: "mt-5 flex items-center justify-center gap-2 text-xs text-violet-300 transition hover:text-[#a78bfa]",
};
