export const careerDetailsTheme = {
  main: "min-h-screen bg-[#ffffff]",
  heroSection: "relative overflow-hidden bg-[#111827]",
  heroImageWrapper: "absolute inset-0",
  heroImage: "object-cover opacity-25",
  heroOverlay: "absolute inset-0 bg-linear-to-r from-[#111827] via-[#111827]/90 to-[#111827]/40",
  heroContainer: "relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28",
  backLink: "mb-8 inline-flex items-center gap-2 text-sm font-medium text-[#93c5fd]/80 transition hover:text-[#93c5fd]",
  backIcon: "h-4 w-4 rtl:rotate-180",
  role: "mb-3 text-sm font-semibold normal-case tracking-wide text-[#2563eb]",
  title: "max-w-4xl font-sans text-4xl tracking-tight text-[#ffffff] sm:text-5xl lg:text-6xl",
  metaWrapper: "mt-8 flex flex-wrap gap-3",
  badge: "rounded-lg border border-[#93c5fd]/30 bg-white/5 px-4 py-2 text-sm text-[#ffffff] backdrop-blur",
  contentSection: "mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8",
  grid: "grid gap-10 lg:grid-cols-[1fr_350px]",
  card: "rounded-lg border border-[#2563eb]/15 bg-white p-6 shadow-sm sm:p-10",
  sectionTitle: "font-sans text-2xl text-[#111827]",
  description: "mt-5 whitespace-pre-line text-base leading-8 text-slate-600",
  requirementsSection: "mt-12 border-t border-[#2563eb]/15 pt-10",
  requirementsList: "mt-6 space-y-4",
  requirementItem: "flex gap-4 text-slate-600",
  requirementIcon: "mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#2563eb]/10 text-xs font-bold text-[#2563eb]",
  requirementText: "leading-7",
  sidebar: "h-fit lg:sticky lg:top-8",
  sidebarCard: "rounded-lg border border-[#2563eb]/15 bg-white p-6 shadow-sm",
  sidebarTitle: "font-sans text-xl text-[#111827]",
  sidebarDescription: "mt-3 text-sm leading-6 text-slate-500",
  applyButton: "mt-6 w-full rounded-lg bg-[#111827] px-5 py-3.5 text-sm font-semibold normal-case tracking-wide text-[#93c5fd] transition hover:bg-[#1e293b] text-center block",
  viewAllButton: "mt-3 flex w-full items-center justify-center rounded-lg border border-[#2563eb]/30 px-5 py-3.5 text-sm font-semibold text-[#111827] transition hover:bg-[#eff6ff]",
};
